# Archivo: compose.yaml
version: '3.8'

services:
  app-api:
    image: detail-shop-api:latest
    container_name: detail-shop-container
    build: . # Indica a Compose que construya la imagen usando el Dockerfile en el directorio actual
    ports:
      - "8080:8080"
    # Sobrescribir las variables de Spring Boot directamente aquí
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://host.docker.internal:5432/db_detail_shop}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-postgres}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-QkRHOjA5MDlUZXN0RzkwOTBCR0Q5MDkwVGVzdEc5MDkwQkdENTkwOTA=}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${GOOGLE_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${GOOGLE_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_ID=${FACEBOOK_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_SECRET=${FACEBOOK_SECRET}
     
    restart: always # Opcional: Reinicia automáticamente si falla