spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_detail_shop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
server.servlet.context-path=/app

# Configuracion de Seguridad JWT
application.security.jwt.secret-key=${JWT_SECRET_KEY:QkRHOjA5MDlUZXN0RzkwOTBCR0Q5MDkwVGVzdEc5MDkwQkdENTkwOTA=}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

# Configuracion de JPA/Hibernate (muy recomendable)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Esto permite que Hibernate agrupe los inserts en una sola sentencia SQL
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

# Configuracion del esquema por defecto (si lo necesitas)
spring.jpa.properties.hibernate.default_schema=local
spring.jpa.open-in-view=false


spring.servlet.multipart.enabled=true
# Tamaño máximo del archivo (ajústalo según necesites)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Muestra los detalles de por qué falló el mapeo del JSON
logging.level.org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod=DEBUG
logging.level.org.springframework.web.bind.annotation.support.HandlerMethodInvoker=DEBUG
# Esta es la clave para ver errores de lectura de mensajes
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG